apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  schedule: "* * * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-cronjob
            image: 707768507475.dkr.ecr.us-west-2.amazonaws.com/eks-demo:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
  
