name: Test and Build

on:
  push:
    branches:
      - '**'        
      - '!main'   
      
jobs:

  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install
        
    - name: Run tests
      run: |
        pipenv run pytest

    - name: Build the Docker image
      run: docker build -t docker-test .

