permissions:
  id-token: write
  contents: read

name: Build and Deploy

on:
  pull_request:
    types:
      - closed

jobs:

  if-merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: eks-demo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
       
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'
      id: install
      
    - name: Update kube config
      env: 
        EKS_CLUSTER: test-cluster
      run: aws eks update-kubeconfig --name $EKS_CLUSTER --region  ${{ secrets.AWS_REGION }}
      
    - name: Deploy to EKS
      run: | 
        kubectl apply -f deployment.yaml
        kubectl get cronjob test-cronjob

        

       

